baseURL = "https://scverse.org/"
languageCode = "en-us"
title = "scverse"
description = "Foundational tools for omics data in the life sciences"

[params]
images = ["img/scverse-social-card.png"]

[taxonomies]
    series = 'series'

[markup.goldmark.renderer]
unsafe= true

[outputs]
home = ["HTML", "RSS", "LLMS"]

[outputFormats.LLMS]
mediaType = "text/plain"
baseName = "llms"
isPlainText = true
